project:
  type: book
  output-dir: "docs"
  render:
    - "status.qmd"
    - "users.qmd"
    - "institutions.qmd"
    - "volumes.qmd"
    - "sessions-folders.qmd"

book:
  title: "User Acceptance Testing (UAT) for `databraryr`"
  author: ["Rick Gilmore"]
  date: last-modified
  chapters:
    - index.qmd
    - part: "Authorized Investigators"
      chapters:
      - status.qmd
      - institutions.qmd
      - users.qmd
      - volumes.qmd
      - sessions-folders.qmd
    # - part: "Owners & Admins"
    #   chapters:
    #   - upload.qmd
    #   - admin.qmd
format:
  html:
    theme: cosmo
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 4
