---
title: "Institutions"
format: html
---

## About

This page documents testing of functions related to institutions.

## Setup

```{r}
#| label: "login to Databrary"
library(databraryr)

login_db(email = Sys.getenv("DATABRARY_LOGIN"),
         password = Sys.getenv("DATABRARY_PASSWORD"),
         client_id = Sys.getenv("DATABRARY_CLIENT_ID"),
         client_secret = Sys.getenv("DATABRARY_CLIENT_SECRET"),
         store = FALSE,
         overwrite = FALSE,
         vb = TRUE)
```

## Testing `_institution*` functions

```{r}
#| label: "testing _institution* functions"
get_institution_avatar(institution_id = 1, 
                       dest_path = "databrary.png",
                       vb = TRUE)      
get_institution_by_id(institution_id = 12,
                      vb = TRUE)  
list_institution_affiliates(institution_id = 12,
                            vb = TRUE)
list_institutions(search_string = "The Pennsylvania",
                  vb = TRUE)

```

## Clean-up

```{r}
logout_db()
```